config/routes.rb
Rails.application.routes.draw do
  
  root 'players#index'
  resources :players

  get '/topfives' => 'players#topfives'

  get '/fdupload' => 'playerdata#fd_upload'
  post '/fdimport' => 'playerdata#fd_import'

  get '/proj_upload' => 'playerdata#proj_upload'

  post '/yahoo_proj_import' => 'playerdata#yahoo_proj_import'
  post '/fantasypros_proj_import' => 'playerdata#fantasypros_proj_import'
  post '/rotoworld_proj_import' => 'playerdata#rotoworld_proj_import'
  post '/fantasyanalytics_proj_import' => 'playerdata#fantasyanalytics_proj_import'
  get '/nerds_proj_import' => 'playerdata#nerds_proj_import'

  post '/ownership_import' => 'playerdata#ownership_import'

  get 'csv_output' => 'playerdata#csv_output'
  get 'ceil_output' => 'playerdata#ceil_output'
  get 'floor_output' => 'playerdata#floor_output'

  get 'lineup_builder' => 'playerdata#lineup_builder'
  post 'roto_convert_floor' => 'playerdata#roto_convert_floor'
  post 'roto_convert_ceil' => 'playerdata#roto_convert_ceil'
  post 'roto_convert_ave' => 'playerdata#roto_convert_ave'

  get 'opp_upload' => 'opponents#opp_upload'
  post 'opponents_import' => 'opponents#opponents_import'

  delete 'slate_one_kill' => 'playerdata#slate_one_kill'
  delete 'monday_night_kill' => 'playerdata#monday_night_kill'
  delete 'one_pm_kill' => 'playerdata#one_pm_kill'
  delete 'late_kill' => 'playerdata#late_kill'

end

app/models/player.rb
class Player < ActiveRecord::Base
  validates :name, presence: true

  belongs_to :opponent

  #get players to display:
  def self.by_ave_value(players)
    players = players.sort_by {|p|
      if p.projected_points.length == 0
        0
      else
        p.player_value
      end
    }
    players.reject {|p| p.projected_points.length == 0 || average_points(p.projected_points) < 5}
  end

  def self.by_ave_points(players)
    players = players.sort_by {|p|
      if p.projected_points.length == 0
        0
      else
        average_points(p.projected_points)
      end
    }
    players.reject {|p| p.projected_points.length == 0 || average_points(p.projected_points) < 5}.reverse
  end

  #benchmarks:

  def self.ave_player_at_pos(players)
    ave_player = {}
    total_points = 0
    total_sal = 0
    total_cpp = 0
    total_ceil = 0
    total_floor = 0

    players.each do |p|
      total_points += average_points(p.projected_points)
      total_sal += p.salary
      total_cpp += p.player_value
      total_ceil += p.projected_points.max
      total_floor += p.projected_points.min
    end

    ave_player[:points] = total_points/players.length
    ave_player[:salary] = total_sal/players.length
    ave_player[:value] = total_cpp/players.length
    ave_player[:ceiling] = total_ceil/players.length
    ave_player[:floor] = total_floor/players.length

    ave_player
  end

#top_5_finder
  def self.top_5s
    players = Player.all

    qbs = players.select{|p| p.position == 'QB'}
    wrs = players.select{|p| p.position == 'WR'}
    rbs = players.select{|p| p.position == 'RB'}
    tes = players.select{|p| p.position == 'TE'}
    ds = players.select{|p| p.position == 'D'}
    ks = players.select{|p| p.position == 'K'}

    arr = [tops_at_pos(qbs),
           tops_at_pos(wrs),
           tops_at_pos(rbs),
           tops_at_pos(tes),
           tops_at_pos(ds),
           tops_at_pos(ks)]     
  end

  def self.top5_details(matrix)
    details_obj = {}
    positions = ['QB','WR','RB','TE','D','K']
    cats = ['Top Ave Projection', 'Top Ave Value', 'Top Ceiling', 'Top floor', 
            'Top Dropoff', 'Top Cost Per Addition Point', 'Top DO to 5th player', 'Top CAP to 5th Player' ]

    i = 0
    j = 0
    matrix.each do |pos_arr|
      details_obj[positions[i]] = {}
        pos_arr.each do |top5_cat|
          cat = cats[j]
          details_obj[positions[i]][cat] = []
          top5_cat.each do |player|
            details_obj[positions[i]][cat] << player.name
          end
          j += 1
        end
      j = 0  
      i += 1
    end
    details_obj
  end

  def self.top_counts(matrix)
    result_obj = {}

    matrix.each do |pos_arr|
      pos_hash = Hash.new(0)
        position = pos_arr[0][0].position
        pos_arr.each do |top5_for_metric|
            top5_for_metric.each do |p|
              pos_hash[p.name] += 1
            end
        end
      result_obj[position] = pos_hash
    end

    result_obj
  end

#helpers:

  def player_value
    if self.projected_points.length == 0 || Player.average_points(self.projected_points) < 5
      0
    else
      self.salary/Player.average_points(self.projected_points)
    end
  end

  def self.average_points(arr)
    arr.reduce(0, :+)/arr.length
  end

  def self.tops_at_pos(players_at_pos)
    top_ave_proj = Player.by_ave_points(players_at_pos).first(5)
    top_ave_value = Player.by_ave_value(players_at_pos).first(5)
    top_ceilings = top5_ceiling_helper(players_at_pos)
    top_floors =  top5_floor_helper(players_at_pos)
    top_dropoffs =  top5_dropoff_helper(players_at_pos)
    top_cap =  top5_cap_helper(players_at_pos)
    top_dropoffs_5 = top5_dropoff_5_helper(players_at_pos)
    top_cap_5 = top5_cap_5_helper(players_at_pos)

    [top_ave_proj, top_ave_value, top_ceilings, top_floors, top_dropoffs, top_cap, top_dropoffs_5, top_cap_5]
  end

  def self.top5_ceiling_helper(players)
    players.sort_by{|p| p.projected_points.max || 0}.reverse.first(5)
  end

  def self.top5_floor_helper(players)
    players.sort_by{|p| p.projected_points.min || 0}.reverse.first(5)
  end

  def self.top5_dropoff_helper(players)
    players.sort_by{|p| p.dropoff || 0}.reverse.first(5)
  end

  def self.top5_cap_helper(players)
    players.reject!{|n| n.cap.to_s == 'NaN' || n.cap == nil}
    players.sort_by{|p| p.cap.round(2) || 0}.first(5)
  end

  def self.top5_dropoff_5_helper(players)
    players.sort_by{|p| p.dropoff_5 || 0}.reverse.first(5)
  end

  def self.top5_cap_5_helper(players)
    players.sort_by{|p| p.cap_5 || 0}.first(5)
  end

  def self.create_player_dropoffs(players)
    players = players.reject {|p| p.projected_points.length == 0 || average_points(p.projected_points) < 5}
    players.sort_by!{|p| Player.average_points(p.projected_points)}.reverse!
    
    players.each_with_index do |p, i|
      p.dropoff = average_points(p.projected_points) - average_points(players[i+1].projected_points) unless !players[i+1]
      p.cap =  (p.salary - players[i+1].salary)/p.dropoff unless !players[i+1]
      p.dropoff_5 = average_points(p.projected_points) - average_points(players[i+5].projected_points) unless !players[i+5]
      p.cap_5 = (p.salary - players[i+5].salary)/p.dropoff_5 unless !players[i+5]
      p.save
    end
  end

  def self.create_all_players_dropoffs(qbs,wrs,rbs,tes,ks,ds)
    Player.create_player_dropoffs(qbs)
    Player.create_player_dropoffs(wrs)
    Player.create_player_dropoffs(rbs)
    Player.create_player_dropoffs(tes)
    Player.create_player_dropoffs(ks)
    Player.create_player_dropoffs(ds)
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  require 'csv'

  def index
    players = Player.by_ave_points(Player.all)
    @qbs = players.select {|p| p.position == 'QB'}
      @ave_qb = Player.ave_player_at_pos(@qbs)
      @top_10_qb = Player.ave_player_at_pos(@qbs.sort_by{ |p| p.salary}.last(10))
    @wrs = players.select {|p| p.position == 'WR'}
      @ave_wr = Player.ave_player_at_pos(@wrs)
      @top_10_wr = Player.ave_player_at_pos(@wrs.sort_by{ |p| p.salary}.last(10))
    @rbs = players.select {|p| p.position == 'RB'}
      @ave_rb = Player.ave_player_at_pos(@rbs)
      @top_10_rb = Player.ave_player_at_pos(@rbs.sort_by{ |p| p.salary}.last(10))
    @tes = players.select {|p| p.position == 'TE'}
      @ave_te = Player.ave_player_at_pos(@tes)
      @top_10_te = Player.ave_player_at_pos(@tes.sort_by{ |p| p.salary}.last(10))
    @ds = players.select {|p| p.position == 'D'}
      @ave_d = Player.ave_player_at_pos(@ds)
      @top_10_d = Player.ave_player_at_pos(@ds.sort_by{ |p| p.salary}.last(10))
    @ks = players.select {|p| p.position == 'K'}
      @ave_k = Player.ave_player_at_pos(@ks)
      @top_10_k = Player.ave_player_at_pos(@ks.sort_by{ |p| p.salary}.last(10))
    Player.create_all_players_dropoffs(@qbs,@wrs,@rbs,@tes,@ks,@ds)
  end

  def show
  end

  def topfives
    top_5s_matrix = Player.top_5s
    @top_5s_details = Player.top5_details(top_5s_matrix)
    @counts = Player.top_counts(top_5s_matrix)
  end

end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/index.html.erb
  <div id='csv_links'>
    <%=button_to('GoodBye Ruby Thursday', slate_one_kill_path, method: :delete)%>
    <%=button_to('Exclude Monday', monday_night_kill_path, method: :delete)%>
    <%=button_to('Kill 1', one_pm_kill_path, method: :delete)%>
    <%=button_to('Kill 4', late_kill_path, method: :delete)%>
  </div>  

  <table>
    <tr>
      <th align="left">Name</th>
      <th align="left">Position</th>
      <th align="left">Team v Opponent</th>
      <th align="left">Ave Points</th> 
      <th align="left">Salary</th>
      <th align="left">CPP</th>
      <th align="left">Ceiling</th>
      <th align="left">Floor</th>
      <th align="left">DO, CAP, DO_5, CAP_5</th>
      <th align="left">Ownership</th>
      <th align="left">DEF Adjustor</th>
    </tr>
    <tr>
      <td class='benchmark'>Ave QB</td>
      <td class='benchmark'>QB</td>
      <td class='benchmark'>all</td>
      <td class='benchmark'><%='%.2f' % (@ave_qb[:points]) %></td> 
      <td class='benchmark'><%=@ave_qb[:salary]%></td>
      <td class='benchmark'><%='%.2f' % (@ave_qb[:value])%></td>
      <td class='benchmark'><%='%.2f' % @ave_qb[:ceiling]%></td>
      <td class='benchmark'><%='%.2f' % @ave_qb[:floor]%></td>
    </tr>
    <tr>
      <td class='benchmark'>Top 10 QB</td>
      <td class='benchmark'>QB</td>
      <td class='benchmark'>all</td>
      <td class='benchmark'><%='%.2f' % (@top_10_qb[:points]) %></td> 
      <td class='benchmark'><%=@top_10_qb[:salary]%></td>
      <td class='benchmark'><%='%.2f' % (@top_10_qb[:value])%></td>
      <td class='benchmark'><%='%.2f' % @top_10_qb[:ceiling]%></td>
      <td class='benchmark'><%='%.2f' % @top_10_qb[:floor]%></td>
    </tr>
    <% @qbs.each do |p| %>
      <tr>
        <td><%=p.name%></td>
        <td><%=p.position%></td>
        <td><%=p.team%> v. <%=p.opponent.team%></td>
        <td><%='%.2f' % (Player.average_points(p.projected_points)) unless p.projected_points.length == 0 %></td> 
        <td><%=p.salary%></td>
        <td><%='%.2f' % (p.player_value)%></td>
        <td><%=p.projected_points.max%></td>
        <td><%=p.projected_points.min%></td>
        <td><%="#{p.dropoff.round(2) unless !p.dropoff}, #{p.cap.round(2) unless !p.cap}, #{p.dropoff_5.round(2)unless !p.dropoff_5}, #{p.cap_5.round(2) unless !p.cap_5}"%></td>
        <td><%=p.ownership%></td>
        <td><%=p.opponent.send(p.position.downcase)%></td>
      </tr>
    <% end %>
  </table>

<br>
<hr>
<br>

  <table>
    <tr>
      <th align="left">Name</th>
      <th align="left">Position</th>
      <th align="left">Team</th>
      <th align="left">Ave Points</th> 
      <th align="left">Salary</th>
      <th align="left">CPP</th>
      <th align="left">Ceiling</th>
      <th align="left">Floor</th>
      <th align="left">DO, CAP, DO_5, CAP_5</th>
      <th align="left">Ownership</th>
    </tr>
    <tr>
      <td class='benchmark'>Ave WR</td>
      <td class='benchmark'>WR</td>
      <td class='benchmark'>all</td>
      <td class='benchmark'><%='%.2f' % (@ave_wr[:points]) %></td> 
      <td class='benchmark'><%=@ave_wr[:salary]%></td>
      <td class='benchmark'><%='%.2f' % (@ave_wr[:value])%></td>
      <td class='benchmark'><%='%.2f' % @ave_wr[:ceiling]%></td>
      <td class='benchmark'><%='%.2f' % @ave_wr[:floor]%></td>
    </tr>
    <tr>
      <td class='benchmark'>Top 10 WR</td>
      <td class='benchmark'>WR</td>
      <td class='benchmark'>all</td>
      <td class='benchmark'><%='%.2f' % (@top_10_wr[:points]) %></td> 
      <td class='benchmark'><%=@top_10_wr[:salary]%></td>
      <td class='benchmark'><%='%.2f' % (@top_10_wr[:value])%></td>
      <td class='benchmark'><%='%.2f' % @top_10_wr[:ceiling]%></td>
      <td class='benchmark'><%='%.2f' % @top_10_wr[:floor]%></td>
    </tr>
    <% @wrs.each do |p| %>
      <tr>
        <td><%=p.name%></td>
        <td><%=p.position%></td>
        <td><%=p.team%> v. <%=p.opponent.team%></td>
        <td><%='%.2f' % (p.projected_points.reduce(0, :+)/p.projected_points.length) unless p.projected_points.length == 0 %></td>
        <td><%=p.salary%></td>
        <td><%='%.2f' % (p.player_value)%></td>
        <td><%=p.projected_points.max%></td>
        <td><%=p.projected_points.min%></td>
        <td><%="#{p.dropoff.round(2) unless !p.dropoff}, #{p.cap.round(2) unless !p.cap}, #{p.dropoff_5.round(2)unless !p.dropoff_5}, #{p.cap_5.round(2) unless !p.cap_5}"%></td>
        <td><%=p.ownership%></td>
        <td><%=p.opponent.send(p.position.downcase)%></td>
      </tr>
    <% end %>
  </table>
  
<br>
<hr>
<br>

  <table>
    <tr>
      <th align="left">Name</th>
      <th align="left">Position</th>
      <th align="left">Team</th>
      <th align="left">Ave Points</th> 
      <th align="left">Salary</th>
      <th align="left">CPP</th>
      <th align="left">Ceiling</th>
      <th align="left">Floor</th>
      <th align="left">DO, CAP, DO_5, CAP_5</th>
      <th align="left">Ownership</th>
    </tr>
    <tr>
      <td class='benchmark'>Ave RB</td>
      <td class='benchmark'>RB</td>
      <td class='benchmark'>all</td>
      <td class='benchmark'><%='%.2f' % (@ave_rb[:points]) %></td> 
      <td class='benchmark'><%=@ave_rb[:salary]%></td>
      <td class='benchmark'><%='%.2f' % (@ave_rb[:value])%></td>
      <td class='benchmark'><%='%.2f' % @ave_rb[:ceiling]%></td>
      <td class='benchmark'><%='%.2f' % @ave_rb[:floor]%></td>
    </tr>
    <tr>
      <td class='benchmark'>Top 10 RB</td>
      <td class='benchmark'>RB</td>
      <td class='benchmark'>all</td>
      <td class='benchmark'><%='%.2f' % (@top_10_rb[:points]) %></td> 
      <td class='benchmark'><%=@top_10_rb[:salary]%></td>
      <td class='benchmark'><%='%.2f' % (@top_10_rb[:value])%></td>
      <td class='benchmark'><%='%.2f' % @top_10_rb[:ceiling]%></td>
      <td class='benchmark'><%='%.2f' % @top_10_rb[:floor]%></td>
    </tr>
    <% @rbs.each do |p| %>
      <tr>
        <td><%=p.name%></td>
        <td><%=p.position%></td>
        <td><%=p.team%> v. <%=p.opponent.team%></td>
        <td><%='%.2f' % (p.projected_points.reduce(0, :+)/p.projected_points.length) unless p.projected_points.length == 0 %></td>
        <td><%=p.salary%></td>
        <td><%='%.2f' % (p.player_value)%></td>
        <td><%=p.projected_points.max%></td>
        <td><%=p.projected_points.min%></td>
        <td><%="#{p.dropoff.round(2) unless !p.dropoff}, #{p.cap.round(2) unless !p.cap}, #{p.dropoff_5.round(2)unless !p.dropoff_5}, #{p.cap_5.round(2) unless !p.cap_5}"%></td>
        <td><%=p.ownership%></td>
        <td><%=p.opponent.send(p.position.downcase)%></td>
      </tr>
    <% end %>
  </table>
  
<br>
<hr>
<br>

  <table>
    <tr>
      <th align="left">Name</th>
      <th align="left">Position</th>
      <th align="left">Team</th>
      <th align="left">Ave Points</th> 
      <th align="left">Salary</th>
      <th align="left">CPP</th>
      <th align="left">Ceiling</th>
      <th align="left">Floor</th>
      <th align="left">DO, CAP, DO_5, CAP_5</th>
      <th align="left">Ownership</th>
    </tr>
    <tr>
      <td class='benchmark'>Ave TE</td>
      <td class='benchmark'>TE</td>
      <td class='benchmark'>all</td>
      <td class='benchmark'><%='%.2f' % (@ave_te[:points]) %></td> 
      <td class='benchmark'><%=@ave_te[:salary]%></td>
      <td class='benchmark'><%='%.2f' % (@ave_te[:value])%></td>
      <td class='benchmark'><%='%.2f' % @ave_te[:ceiling]%></td>
      <td class='benchmark'><%='%.2f' % @ave_te[:floor]%></td>
    </tr>
    <tr>
      <td class='benchmark'>Top 10 TE</td>
      <td class='benchmark'>TE</td>
      <td class='benchmark'>all</td>
      <td class='benchmark'><%='%.2f' % (@top_10_te[:points]) %></td> 
      <td class='benchmark'><%=@top_10_te[:salary]%></td>
      <td class='benchmark'><%='%.2f' % (@top_10_te[:value])%></td>
      <td class='benchmark'><%='%.2f' % @top_10_te[:ceiling]%></td>
      <td class='benchmark'><%='%.2f' % @top_10_te[:floor]%></td>
    </tr>
    <% @tes.each do |p| %>
      <tr>
        <td><%=p.name%></td>
        <td><%=p.position%></td>
        <td><%=p.team%> v. <%=p.opponent.team%></td>
        <td><%='%.2f' % (p.projected_points.reduce(0, :+)/p.projected_points.length) unless p.projected_points.length == 0 %></td> 
        <td><%=p.salary%></td>
        <td><%='%.2f' % (p.player_value)%></td>
        <td><%=p.projected_points.max%></td>
        <td><%=p.projected_points.min%></td>
        <td><%="#{p.dropoff.round(2) unless !p.dropoff}, #{p.cap.round(2) unless !p.cap}, #{p.dropoff_5.round(2)unless !p.dropoff_5}, #{p.cap_5.round(2) unless !p.cap_5}"%></td>
        <td><%=p.ownership%></td>
        <td><%=p.opponent.send(p.position.downcase)%></td>
      </tr>
    <% end %>
  </table>
  
<br>
<hr>
<br>

  <table>
    <tr>
      <th align="left">Name</th>
      <th align="left">Position</th>
      <th align="left">Team</th>
      <th align="left">Ave Points</th> 
      <th align="left">Salary</th>
      <th align="left">CPP</th>
      <th align="left">Ceiling</th>
      <th align="left">Floor</th>
      <th align="left">DO, CAP, DO_5, CAP_5</th>
      <th align="left">Ownership</th>
    </tr>
    <tr>
      <td class='benchmark'>Ave DEF</td>
      <td class='benchmark'>DEF</td>
      <td class='benchmark'>all</td>
      <td class='benchmark'><%='%.2f' % (@ave_d[:points]) %></td> 
      <td class='benchmark'><%=@ave_d[:salary]%></td>
      <td class='benchmark'><%='%.2f' % (@ave_d[:value])%></td>
      <td class='benchmark'><%='%.2f' % @ave_d[:ceiling]%></td>
      <td class='benchmark'><%='%.2f' % @ave_d[:floor]%></td>
    </tr>
    <tr>
      <td class='benchmark'>Top 10 DEF</td>
      <td class='benchmark'>DEF</td>
      <td class='benchmark'>all</td>
      <td class='benchmark'><%='%.2f' % (@top_10_d[:points]) %></td> 
      <td class='benchmark'><%=@top_10_d[:salary]%></td>
      <td class='benchmark'><%='%.2f' % (@top_10_d[:value])%></td>
      <td class='benchmark'><%='%.2f' % @top_10_d[:ceiling]%></td>
      <td class='benchmark'><%='%.2f' % @top_10_d[:floor]%></td>
    </tr>
    <% @ds.each do |p| %>
      <tr>
        <td><%=p.name%></td>
        <td><%=p.position%></td>
        <td><%=p.team%> v. <%=p.opponent.team%></td>
        <td><%='%.2f' % (p.projected_points.reduce(0, :+)/p.projected_points.length) unless p.projected_points.length == 0 %></td>
        <td><%=p.salary%></td>
        <td><%='%.2f' % (p.player_value)%></td>
        <td><%=p.projected_points.max%></td>
        <td><%=p.projected_points.min%></td>
        <td><%="#{p.dropoff.round(2) unless !p.dropoff}, #{p.cap.round(2) unless !p.cap}, #{p.dropoff_5.round(2)unless !p.dropoff_5}, #{p.cap_5.round(2) unless !p.cap_5}"%></td>
        <td><%=p.ownership%></td>
      </tr>
    <% end %>
  </table>
  
<br>
<hr>
<br>

  <table>
    <tr>
      <th align="left">Name</th>
      <th align="left">Position</th>
      <th align="left">Team</th>
      <th align="left">Ave Points</th> 
      <th align="left">Salary</th>
      <th align="left">CPP</th>
      <th align="left">Ceiling</th>
      <th align="left">Floor</th>
      <th align="left">DO, CAP, DO_5, CAP_5</th>
      <th align="left">Ownership</th>
    </tr>
    <tr>
      <td class='benchmark'>Ave K</td>
      <td class='benchmark'>K</td>
      <td class='benchmark'>all</td>
      <td class='benchmark'><%='%.2f' % (@ave_k[:points]) %></td> 
      <td class='benchmark'><%=@ave_k[:salary]%></td>
      <td class='benchmark'><%='%.2f' % (@ave_k[:value])%></td>
      <td class='benchmark'><%='%.2f' % @ave_k[:ceiling]%></td>
      <td class='benchmark'><%='%.2f' % @ave_k[:floor]%></td>
    </tr>
    <tr>
      <td class='benchmark'>Top 10 K</td>
      <td class='benchmark'>K</td>
      <td class='benchmark'>all</td>
      <td class='benchmark'><%='%.2f' % (@top_10_k[:points]) %></td> 
      <td class='benchmark'><%=@top_10_k[:salary]%></td>
      <td class='benchmark'><%='%.2f' % (@top_10_k[:value])%></td>
      <td class='benchmark'><%='%.2f' % @top_10_k[:ceiling]%></td>
      <td class='benchmark'><%='%.2f' % @top_10_k[:floor]%></td>
    </tr>
    <% @ks.each do |p| %>
      <tr>
        <td><%=p.name%></td>
        <td><%=p.position%></td>
        <td><%=p.team%> v. <%=p.opponent.team%></td>
        <td><%='%.2f' % (p.projected_points.reduce(0, :+)/p.projected_points.length) unless p.projected_points.length == 0 %></td>
        <td><%=p.salary%></td>
        <td><%='%.2f' % (p.player_value)%></td>
        <td><%=p.projected_points.max%></td>
        <td><%=p.projected_points.min%></td>
        <td><%="#{p.dropoff.round(2) unless !p.dropoff}, #{p.cap.round(2) unless !p.cap}, #{p.dropoff_5.round(2)unless !p.dropoff_5}, #{p.cap_5.round(2) unless !p.cap_5}"%></td>
        <td><%=p.ownership%></td>
      </tr>
    <% end %>
  </table>

app/views/players/react_index.html.erb
<%= react_component 'Players', { data: @players } %>

app/views/players/topfives.html.erb
<table style="width: 100%;">
<%@counts.each do |position, players| %>
  <th><%="#{position}"%></th>
  <td>
    <h5>
      <%players.each do |player, top5count|%>
        <% p = Player.find_by(name: player) %>
        <%= player%> - <%=top5count%> (<%=p.opponent.send(p.position.downcase) unless p.position == 'D' || p.position == 'K'%>)<br>
      <%end%>
    </h5>
  </td>
<%end%>
</table>
<br>

<%@top_5s_details.each do |pos, top5_cats|%>
  <h3><%=pos%></h3>
  <table>
    <%top5_cats.each do |cat, players|%>
      <th style='text-align: left;'><%=cat%></th>
        <tr>
          <%players.each do |p|%>
            <td><%=p%></td>
          <%end%>
        </tr>
    <%end%>
  </table>
<%end%>